name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install --frozen-lockfile
      - run: yarn affected:build --parallel --max-parallel=3
      - run: yarn affected:test --parallel --max-parallel=2
      - run: yarn affected:e2e
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install --frozen-lockfile
      - run: yarn dlx commitlint --from ${{ env.NX_BASE }} --to ${{ env.NX_HEAD }}
      - run: yarn affected:build --parallel --max-parallel=3
      - run: yarn affected:test --parallel --max-parallel=2
      - run: yarn affected:e2e
